//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Heuristic
{
	TDTile goalTileNode;

	public Heuristic()
	{
		goalTileNode = new TDTile ();
	}

	public Heuristic (TDTile goal)
	{
		goalTileNode = goal;
	}

	public void SetGoal(TDTile goal)
	{
		goalTileNode = goal;
	}

	public int EstimateDistance(Vector3 position)
	{
		return (int)Mathf.Abs(position.x - goalTileNode.Pos.x) + 
			(int)Mathf.Abs(position.z - goalTileNode.Pos.z);
		//return (int)Mathf.Abs(node.gameObject.transform.position.x - goalTileNode.gameObject.transform.position.x) + 
		//	(int)Mathf.Abs(node.gameObject.transform.position.z - goalTileNode.gameObject.transform.position.z);
	}
	public int EstimateDistance(TDTile node)
	{
		return (int)Mathf.Abs(node.Pos.x - goalTileNode.Pos.x) + 
			(int)Mathf.Abs(node.Pos.x - goalTileNode.Pos.z);
	}

	public int EstimateDistance(TDTile source, TDTile target)
	{
		return (int)Mathf.Abs(source.Pos.x - target.Pos.x) + 
			(int)Mathf.Abs(source.Pos.z - target.Pos.z);
	}
}